config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'carts/confirm'
  get 'about' => 'users#about', as: "about"
  get 'events/new/:id' => 'events#new', as: 'new_event'
  get 'items/new/:id' => 'items#new', as: 'new_item'

  devise_for :managers
  devise_for :users

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :following_artists, only: [:create, :destroy]
  end
  resources :artists do
    resource :following_artists, only: [:create, :destroy]
    resource :items, only: [:show, :index, :edit, :create, :destroy]
    resource :events, only: [:show, :edit, :update, :create, :destroy]
  end
  resources :items, :only => [:new, :show, :index, :edit, :create, :update, :destroy] do
    resource :carts, only: [:create, :destroy]
  end
  resources :events, :only => [:new, :show, :edit, :create, :update, :destroy]
  resources :discs, :only => [:create, :update, :destroy]
  resources :musics, :only => [:create, :update, :destroy]
  resources :carts, :only => [:index, :create, :update, :destroy]

  resources :histories, :only => [:show, :index, :create, :update] do
    resource :cart_histories, only: [:create, :destroy]
  end
  resources :cart_histories, :only => [:create]
  resources :following_artists, :only => [:index, :show, :create, :destroy]
  resources :labels, :only => [:index, :edit, :new, :create, :update, :destroy]
  resources :genres, :only => [:new, :create, :edit, :update, :destroy]
  resources :types, :only => [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'

end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :following_artists, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :items, dependent: :destroy

	attachment :image

  validates :name, presence: true, length: {maximum: 20}
  validates :name_kana, presence: true, length: {maximum: 30}
  validates :intro, presence: true, length: {maximum: 200}

  def followed_by?(user)
    following_artists.where(user_id: user.id).exists?
  end

  class Artits < ActiveRecord::Base
    paginates_per 5
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :amount, presence: true
end

app/models/cart_history.rb
class CartHistory < ApplicationRecord
  belongs_to :history
  belongs_to :item
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :item
  has_many :musics, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true

  validates :name, presence: true, length: {maximum: 20}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 30}
  validates :detail, presence: true, length: {maximum: 200}
  validates :datetime, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :cart_histories, dependent: :destroy
  accepts_nested_attributes_for :cart_histories, allow_destroy: true

  enum status_id:{receptionist: 0,preparation: 1,shipped: 2,cancel: 3}
  enum payment_id:{no_choice:0 ,credit_card: 1,banking: 2,convenience_store: 3,cash: 4}

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist
  belongs_to :type
  belongs_to :genre
  belongs_to :label

  has_many :cart_histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :discs, dependent: :destroy

	attachment :image

  accepts_nested_attributes_for :discs, allow_destroy: true

  validates :title, presence: true, length: {maximum: 40}
  validates :price, presence: true, length: {maximum: 7}
  validates :stock, presence: true, length: {maximum: 7}

  validates :artist_id, presence: true
  validates :type_id, presence: true
  validates :genre_id, presence: true
  validates :label_id, presence: true

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :items
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :disc

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :following_artists, dependent: :destroy


  validates :name, presence: true, length:{maximum: 20}
  validates :name_kana, presence: true
  validates :postal_code, presence: true, length: {is: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length:{maximum: 11}
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_manager!, only: [:new, :edit, :create, :update, :destroy]

  def new
  	@artist = Artist.new
  end

  def show
  	@artist = Artist.find(params[:id])
    @items = @artist.items.all.reverse_order.limit(3)
    @events = @artist.events.page(params[:page]).per(5).order('datetime ASC')
  end

  def index
    @search = Artist.ransack(params[:q])
    @search_artists = @search.result.page(params[:page]).per(9).reverse_order
  end

  def edit
  	@artist = Artist.find(params[:id])
  end

  def create
  	@artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist.id), notice: 'アーティスト情報を追加しました'
    else
      flash.now[:alert] = 'アーティスト情報の追加に失敗しました'
      render :new
    end
  end

  def update
  	@artist = Artist.find(params[:id])
  	if @artist.update(artist_params)
      redirect_to artist_path(@artist.id), notice: 'アーティスト情報を編集しました'
    else
      flash.now[:alert] = 'アーティスト情報の編集に失敗しました'
      render :edit
    end
  end

  def destroy
  	artist = Artist.find(params[:id])
  	artist.destroy
  	redirect_to artists_path, notice: 'アーティスト情報を削除しました'
  end

  private
  def artist_params
  	params.require(:artist).permit(:name, :name_kana, :image, :intro)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_eventlist.html.erb
<% events.each do |event| %>
  <p><%= simple_time(event.datetime) %> / <%= link_to event.name, event_path(event.id) %></p>
<% end %>

app/views/artists/edit.html.erb
<div class="artist">
	<div>
		<h3 class="artist-header">アーティストプロフィール編集</h3>
	</div>
	<%= form_for(@artist) do |f| %>
	<div class="artist-area">
		<p>アーティスト名：<%= f.text_field :name, class: "profile-item" %></p>
		<p>アーティスト写真
		<%= f.attachment_field :image, class: "profile-item" %></p>
		<p>アーティスト紹介
		<%= f.text_area :intro, size: "60x10", class: "profile-item" %></p>
	</div>
	<div class="artist-footer">
		<%= f.submit '更新', class: "btn btn-primary" %>
		<%= link_to '戻る', artist_path, class: "btn btn-default" %>
		<%= link_to 'アーティストの削除', artist_path(@artist.id),	 class: "d-btn btn btn-danger artist-profile", method: :delete %>
	</div>
	<% end %>
</div>

app/views/artists/index.html.erb
<h3>アーティスト一覧
  <% if manager_signed_in? %>
    <%= link_to "新規追加", new_artist_path, class:"d-btn btn btn-default new-btn artist-new" %>
  <% end %>
</h3>

<div class="center-block">
  <!-- 検索バー -->
  <%= search_form_for @search do |f| %>
    <%= f.search_field :name_cont, placeholder: 'アーティスト名で検索' %>
    <%= f.submit ("検索") , class: 'd-btn'%>
  <% end %>
  <!-- 一覧表示 -->
  <div class="center-block-artists">
    <% @search_artists.each do |artist| %>
      <div class="thumbnail-contents">
        <div class="item-box2">
          <%= link_to artist_path(artist.id) do %>
            <%= attachment_image_tag artist, :image, :fill, 400, 400, class:"contents-item" %>
          <% end %>
          <br>
          <div class="artist-profile"><font size="4"><%= link_to artist.name, artist_path(artist.id) %></font></div>
        </div>

      </div>
    <% end %>
    <%= paginate @search_artists, class: "paginate" %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="artist">
  <div>
    <h3 class="artist-header">アーティスト新規追加</h3>
  </div>
  <%= form_for(@artist) do |f| %>
  <div class="artist-area">
    <p>アーティスト名：<%= f.text_field :name, placeholder:"アーティスト名", class: "profile-item" %></p>
    <p>アーティスト名(カナ)：<%= f.text_field :name_kana, placeholder:"アーティスト名(カナ)" %></p>
    <p>アーティスト写真
    <%= f.attachment_field :image, class: "profile-item" %></p>
    <p>アーティスト紹介
    <%= f.text_area :intro, size: "60x10", placeholder:"アーティスト紹介", class: "profile-item" %></p>
  </div>

  <div class="artist-footer">
    <%= f.submit '保存', class: "btn btn-primary" %>
    <%= link_to '戻る', artists_path, class:"d-btn btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<h3>アーティスト詳細</h3>
<div class="center-block">

  <div class="profile">
    <%= attachment_image_tag @artist, :image, :fill, 300, 300, class:"artist-block" %>
    <div class="artist-intro artist-block">
      <div class="artist-name">
        <%= @artist.name %>
        <div class="artist-title">
          <% if user_signed_in? %>
            <% if @artist.followed_by?(current_user) %>
              <%= link_to artist_following_artists_path(@artist), class: "follow-btn followed", method: :delete, "data-confirm" => "フォローを外しますか？" do %>
                <span>フォロー中</span>
              <% end %>

            <% else %>
              <%= link_to artist_following_artists_path(@artist), class: "follow-btn", method: :post do %>
                <span class="d-btn"><i class="fas fa-plus"></i>フォローする</span>
              <% end %>
            <% end %>

          <% elsif manager_signed_in? %>
            <%= link_to edit_artist_path do %>
              <i class="fas fa-cogs edit-btn"></i>
            <% end %>
          <% else %>
          <% end %>
        </div>
      </div>
      <%= @artist.intro %>
    </div>
  </div>

  <div class="artist-show-item">
    <h4 class="artist-show">CD情報</h4>
    <% if manager_signed_in? %>
      <%= link_to "新規追加", new_item_path(@artist.id), class:"d-btn btn btn-default new-btn artist-show" %>
    <% end %>
  </div>
  <% @items.each do |item| %>
    <div class="thumbnail-contents">
      <%= link_to (item_path(item.id)) do %>
        <%= attachment_image_tag item, :image, class:"contents-item", fallback: "no_image.png" %>
        <font size="4"><b><%= item.title %></b></font>
        <div><%= item.artist.name %></div>
        <div>
            <div class="new-soldout">
                <!-- 日付の比較 -->
                  <% create_day = item.created_at %>
                  <% today = Time.zone.now %>
                  <% compared_parameter = today - 1.day %>
                  <% if compared_parameter < create_day %>
                    <p class="new-item">!NEW!</p>
                  <% elsif item.stock == 0 %>
                    <font color="red"><b>売切</b></font>
                  <% else %>
                    <p>　　　</p>
                  <% end %>
                <!-- 日付の比較ここまで -->
            </div>
            <div class="item-index-price"><%= item.price %>円(税込)</div>
          </div>
      <% end %>
    </div>
  <% end %>


  <div class="more-btn"><%= link_to 'もっと見る', "/items?utf8=✓&q%5Bartist_name_cont%5D=#{@artist.name}", class: "btn btn-primary" %></div>

  <div class="artist-show-item">
    <h4 class="artist-show">イベント情報</h4>
    <% if manager_signed_in? %>
      <%= link_to 'イベント追加', new_event_path(@artist.id), class:"d-btn btn btn-default new-btn artist-show" %>
    <% end %>
  </div>

  <div id ="events">
    <%= render 'artists/eventlist', events: @events %>
  </div>

  <%= link_to_next_page @events, 'もっと見る', remote: true, id: 'more_link' %>

</div>

app/views/artists/show.js.erb
// Artists#Show イベント情報→「もっと見る」
$('#events').append("<%= escape_javascript(render 'artists/eventlist', events: @events) %>");
$('#more_link').replaceWith("<%= escape_javascript(link_to_next_page @events, 'もっと見る', remote: true, id: 'more_link') %>");