config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'carts/confirm'
  get 'about' => 'users#about', as: "about"
  get 'events/new/:id' => 'events#new', as: 'new_event'
  get 'items/new/:id' => 'items#new', as: 'new_item'

  devise_for :managers
  devise_for :users

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :following_artists, only: [:create, :destroy]
  end
  resources :artists do
    resource :following_artists, only: [:create, :destroy]
    resource :items, only: [:show, :index, :edit, :create, :destroy]
    resource :events, only: [:show, :edit, :update, :create, :destroy]
  end
  resources :items, :only => [:new, :show, :index, :edit, :create, :update, :destroy] do
    resource :carts, only: [:create, :destroy]
  end
  resources :events, :only => [:new, :show, :edit, :create, :update, :destroy]
  resources :discs, :only => [:create, :update, :destroy]
  resources :musics, :only => [:create, :update, :destroy]
  resources :carts, :only => [:index, :create, :update, :destroy]

  resources :histories, :only => [:show, :index, :create, :update] do
    resource :cart_histories, only: [:create, :destroy]
  end
  resources :cart_histories, :only => [:create]
  resources :following_artists, :only => [:index, :show, :create, :destroy]
  resources :labels, :only => [:index, :edit, :new, :create, :update, :destroy]
  resources :genres, :only => [:new, :create, :edit, :update, :destroy]
  resources :types, :only => [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'

end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :following_artists, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :items, dependent: :destroy

	attachment :image

  validates :name, presence: true, length: {maximum: 20}
  validates :name_kana, presence: true, length: {maximum: 30}
  validates :intro, presence: true, length: {maximum: 200}

  def followed_by?(user)
    following_artists.where(user_id: user.id).exists?
  end

  class Artits < ActiveRecord::Base
    paginates_per 5
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :amount, presence: true
end

app/models/cart_history.rb
class CartHistory < ApplicationRecord
  belongs_to :history
  belongs_to :item
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :item
  has_many :musics, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true

  validates :name, presence: true, length: {maximum: 20}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 30}
  validates :detail, presence: true, length: {maximum: 200}
  validates :datetime, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :cart_histories, dependent: :destroy
  accepts_nested_attributes_for :cart_histories, allow_destroy: true

  enum status_id:{receptionist: 0,preparation: 1,shipped: 2,cancel: 3}
  enum payment_id:{no_choice:0 ,credit_card: 1,banking: 2,convenience_store: 3,cash: 4}

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist
  belongs_to :type
  belongs_to :genre
  belongs_to :label

  has_many :cart_histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :discs, dependent: :destroy

	attachment :image

  accepts_nested_attributes_for :discs, allow_destroy: true

  validates :title, presence: true, length: {maximum: 40}
  validates :price, presence: true, length: {maximum: 7}
  validates :stock, presence: true, length: {maximum: 7}

  validates :artist_id, presence: true
  validates :type_id, presence: true
  validates :genre_id, presence: true
  validates :label_id, presence: true

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :items
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :disc

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :following_artists, dependent: :destroy


  validates :name, presence: true, length:{maximum: 20}
  validates :name_kana, presence: true
  validates :postal_code, presence: true, length: {is: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length:{maximum: 11}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_manager!, only: [:new, :edit, :create, :update, :destroy]

  def new
    @event = Event.new
    @artist = Artist.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    @artist = @event.artist
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @event = @artist.events.new(event_params)
  	@event.artist_id = @artist.id
    if @event.save
      redirect_to event_path(@event.id), notice: 'イベントを追加しました'
    else
      flash.now[:alert] = 'イベントの追加に失敗しました'
      render :new
    end
  end

  def update
  	@event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event.id), notice: 'イベントを編集しました'
    else
      flash.now[:alert] = 'イベントの編集に失敗しました'
      render :new
    end
  end

  def destroy
  	event = Event.find(params[:id])
    event.destroy
    redirect_to artists_path, notice: 'イベントを削除しました'
  end

  private

  def event_params
    params.require(:event).permit(:name, :artist_id, :detail, :datetime)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<!-- datetime picker用読込ファイル -->
<!-- CSS -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- JS -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<%= javascript_include_tag 'jquery-ui-timepicker-addon' %>
<%= javascript_include_tag 'jquery-ui-timepicker-ja' %>
<%= stylesheet_link_tag "jquery-ui-timepicker-addon", :media => "all" %>

<div class="event">
  <%= form_for(@event) do |f| %>
    <div>
      <h3 class="event-header">イベント情報編集</h3>
    </div>
    <div class="event-area">
      <table>
          <tr>
            <td class="event-td">イベント名</td>
            <td><%= f.text_field :name %></td>
          </tr>

          <tr>
            <td class="event-td">アーティスト名</td>
            <td><%= @event.artist.name %></td>
          </tr>

          <tr>
            <td class="event-td">開始日時</td>
            <td><%= f.text_field :datetime, id:"datetimepicker" %></td>
          </tr>

          <tr>
            <td class="event-td">イベント紹介文</td>
            <td><%= f.text_area :detail, size: "35x10" %></td>
          </tr>
      </table>
    </div>
    <div class="event-footer">
      <%= f.submit '保存', class:"btn btn-primary" %>
      <%= link_to '戻る', artists_path, class:"btn btn-default" %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<!-- datetime picker用読込ファイル -->
<!-- CSS -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- JS -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<%= javascript_include_tag 'jquery-ui-timepicker-addon' %>
<%= javascript_include_tag 'jquery-ui-timepicker-ja' %>
<%= stylesheet_link_tag "jquery-ui-timepicker-addon", :media => "all" %>

<div class="event">
  <%= form_for [@artist, @event] do |f| %>
  <div>
    <h3 class="event-header">イベント新規追加</h3>
  </div>
  <div class="event-area">
    <table>
        <tr>
          <td class="event-td">イベント名</td>
          <td><%= f.text_field :name, placeholder:"イベント名" %></td>
        </tr>

        <tr>
          <td class="event-td">アーティスト名</td>
          <td><%= @artist.name %></td>
        </tr>

        <tr>
          <td class="event-td">開始日時</td>
          <td><%= f.text_field :datetime, placeholder:"開始日時", id:"datetimepicker" %></td>
        </tr>

        <tr>
          <td class="event-td">イベント紹介文</td>
          <td><%= f.text_area :detail, size: "35x10", placeholder:"イベント紹介文"  %></td>
        </tr>
    </table>
  </div>
  <div class="event-footer">
    <%= f.submit '保存', class:"btn btn-primary" %>
    <%= link_to '戻る', artists_path, class:"btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/events/show.html.erb
<h3>イベント詳細
	<% if manager_signed_in? %>
      <%= link_to edit_event_path do %><i class="fas fa-cogs edit-btn"></i><% end %>
    <% end %>
</h3>
<div class="center-block">
  <div class="event-show-item">
    <%= attachment_image_tag @artist, :image, :fill, 300, 300, class:"event-image" %>
  </div>
  <div class="event-show-item event-show-box2">
    <p class="show-item event-name"><%= @event.name %></p>
    <p class="show-item"><%= simple_time(@event.datetime) %></p>
    <p class="show-item event-detail"><%= @event.detail %></p>
  </div>

  <div class="event-show-box3">
    <div>
      <%= link_to "戻る", artist_path(@artist), class:"btn btn-primary" %>
    </div>
  </div>
</div>