config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'carts/confirm'
  get 'about' => 'users#about', as: "about"
  get 'events/new/:id' => 'events#new', as: 'new_event'
  get 'items/new/:id' => 'items#new', as: 'new_item'

  devise_for :managers
  devise_for :users

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :following_artists, only: [:create, :destroy]
  end
  resources :artists do
    resource :following_artists, only: [:create, :destroy]
    resource :items, only: [:show, :index, :edit, :create, :destroy]
    resource :events, only: [:show, :edit, :update, :create, :destroy]
  end
  resources :items, :only => [:new, :show, :index, :edit, :create, :update, :destroy] do
    resource :carts, only: [:create, :destroy]
  end
  resources :events, :only => [:new, :show, :edit, :create, :update, :destroy]
  resources :discs, :only => [:create, :update, :destroy]
  resources :musics, :only => [:create, :update, :destroy]
  resources :carts, :only => [:index, :create, :update, :destroy]

  resources :histories, :only => [:show, :index, :create, :update] do
    resource :cart_histories, only: [:create, :destroy]
  end
  resources :cart_histories, :only => [:create]
  resources :following_artists, :only => [:index, :show, :create, :destroy]
  resources :labels, :only => [:index, :edit, :new, :create, :update, :destroy]
  resources :genres, :only => [:new, :create, :edit, :update, :destroy]
  resources :types, :only => [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'

end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :following_artists, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :items, dependent: :destroy

	attachment :image

  validates :name, presence: true, length: {maximum: 20}
  validates :name_kana, presence: true, length: {maximum: 30}
  validates :intro, presence: true, length: {maximum: 200}

  def followed_by?(user)
    following_artists.where(user_id: user.id).exists?
  end

  class Artits < ActiveRecord::Base
    paginates_per 5
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :amount, presence: true
end

app/models/cart_history.rb
class CartHistory < ApplicationRecord
  belongs_to :history
  belongs_to :item
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :item
  has_many :musics, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true

  validates :name, presence: true, length: {maximum: 20}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 30}
  validates :detail, presence: true, length: {maximum: 200}
  validates :datetime, presence: true
end

app/models/following_artist.rb
class FollowingArtist < ApplicationRecord
  belongs_to :user
  belongs_to :artist
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :cart_histories, dependent: :destroy
  accepts_nested_attributes_for :cart_histories, allow_destroy: true

  enum status_id:{receptionist: 0,preparation: 1,shipped: 2,cancel: 3}
  enum payment_id:{no_choice:0 ,credit_card: 1,banking: 2,convenience_store: 3,cash: 4}

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist
  belongs_to :type
  belongs_to :genre
  belongs_to :label

  has_many :cart_histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :discs, dependent: :destroy

	attachment :image

  accepts_nested_attributes_for :discs, allow_destroy: true

  validates :title, presence: true, length: {maximum: 40}
  validates :price, presence: true, length: {maximum: 7}
  validates :stock, presence: true, length: {maximum: 7}

  validates :artist_id, presence: true
  validates :type_id, presence: true
  validates :genre_id, presence: true
  validates :label_id, presence: true

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :items
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :disc

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :following_artists, dependent: :destroy


  validates :name, presence: true, length:{maximum: 20}
  validates :name_kana, presence: true
  validates :postal_code, presence: true, length: {is: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length:{maximum: 11}
end

app/controllers/following_artists_controller.rb
class FollowingArtistsController < ApplicationController
  before_action :authenticate_user!

  def index
     @user = User.find(current_user.id)
     @fartists = @user.following_artists.all
     @events = Event.all
     @items = Item.all
  end

  def show
     @user = User.find(current_user.id)
     @fartists = @user.following_artists.all
     @artist = Artist.find(params[:id])
     @events = @artist.events.all
     @items = @artist.items.all
  end

  def create
    artist = Artist.find(params[:artist_id])
    fartist = current_user.following_artists.new(artist_id: artist.id)
    fartist.save
    redirect_to artist_path(artist)
  end

  def destroy
    artist = Artist.find(params[:artist_id])
    follow = current_user.following_artists.find_by(artist_id: artist.id)
    follow.destroy
    redirect_to artist_path(artist)
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/following_artists_helper.rb
module FollowingArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/following_artists/_events.html.erb
<% if events.nil? %>
  <p>アーティストを選択してください。</p>
<% else %>
  <% @events.each do |event| %>
    <%= link_to event_path(event.id) do %>
      <div class="f-list clearfix">
        <div class="f-list-thumbnail">
          <%= attachment_image_tag event.artist, :image, :fill, 60, 60, fallback: "no_image.png" %>
        </div>
        <p class="f-list-text">
          <%= event.name %>
        </p>
      </div>
    <% end %>
  <% end %>
<% end %>

<%= render 'following_artists/events', events: @events %>

app/views/following_artists/_items.html.erb
<% if items.nil? %>
  <p>商品を選択してください。</p>
<% else %>
  <% items.each do |item| %>
  <%= link_to item_path(item) do %>
    <div class="f-list clearfix">
      <div class="f-list-thumbnail">
        <%= attachment_image_tag item, :image, :fill, 60, 60, fallback: "no_image.png"%>
      </div>
        <p class="f-list-text">
          <%= item.title %>
          <%= item.type.name %>
          <!-- <p>NEW</p> -->
        </p>
    </div>
    <% end %>
  <% end %>
<% end %>

<div class="f-list-wrapper">
  </div>

app/views/following_artists/index.html.erb
<div class="follow-artist">
  <div class= "follow-artist-header">
    <h3>フォローアーティスト一覧</h3>
  </div>

  <div class="row">
    <nav class="follow-nav">
      <ul class="main-menu">
        <li class="artist-list">アーティスト名</li>
            <li>
              <% @fartists.each do |fartist| %>
              <%= link_to artist_path(fartist.artist) do %>
              <li class="artist-list">
                <%= attachment_image_tag fartist.artist, :image, :fill, 500, 500, class: "fartist-image" %>
                <%= link_to following_artist_path(fartist.artist.id) do %>
                  <%= fartist.artist.name %>
                <% end %>
              <% end %>
              </li>
            <% end %>
          </li>
      </ul>
    </nav>
  </div>
</div>

app/views/following_artists/show.html.erb
<div class="follow-artist">
  <div class= "follow-artist-header">
    <h3>フォローアーティスト一覧</h3>
  </div>
    <div class="following-box">
      <nav class="follow-nav">

          <ul class="main-menu following-block">
            <li class="event-list">イベント</li>
            <% @events.each do |event| %>
              <%= link_to event_path(event) do %>
                <li class="event-list">
                  <!-- 日付の比較 -->
                    <% create_day = event.created_at %>
                    <% today = Time.zone.now %>
                    <% compared_parameter = today - 1.day %>
                    <% if compared_parameter < create_day %>
                      <p><span class="new-item">!NEW!</span> <%= simple_time(event.datetime) %></p>
                      <p><%= truncate(event.name, length: 12) %></p>
                    <% else %>
                      <p><%= simple_time(event.datetime) %></p>
                      <p><%= truncate(event.name, length: 12) %></p>
                    <% end %>
                  <!-- 日付の比較ここまで -->
                </li>
              <% end %>
            <% end %>
          </ul>

          <ul class="main-menu following-block">
            <li class="artist-list">アーティスト名</li>
            <li>
              <% @fartists.each do |fartist| %>
                <% if fartist.artist_id == @artist.id %>
                  <li class="artist-list current-artist">
                    <%= link_to artist_path(fartist.artist) do %>
                      <%= attachment_image_tag fartist.artist, :image, :fill, 500, 500, class: "fartist-image" %>
                    <% end %>
                    <%= link_to fartist.artist.name, following_artist_path(fartist.artist.id) %>
                  </li>

                <% else %>
                  <%= link_to artist_path(fartist.artist) do %>
                    <li class="artist-list">
                      <%= attachment_image_tag fartist.artist, :image, :fill, 500, 500, class: "fartist-image" %>
                      <%= link_to following_artist_path(fartist.artist.id) do %>
                        <%= fartist.artist.name %>
                      <% end %>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
          </ul>


              <ul class="following-block main-menu">
                <li class="item-list">CD</li>
                  <% @items.each do |item| %>
                    <%= link_to item_path(item) do %>
                      <li class="item-list">
                        <%= attachment_image_tag item, :image, :fill, 500, 500, fallback: "no_image.png", class: "item-images" %>
                        <!-- 日付の比較 -->
                          <% create_day = item.created_at %>
                          <% today = Time.zone.now %>
                          <% compared_parameter = today - 1.day %>
                          <% if compared_parameter < create_day %>
                            <span class="new-item">!NEW!</span> <%= item.title %>
                          <% elsif item.stock == 0 %>
                            <font color="red"><b>売切</b></font> <%= item.title %>
                          <% else %>
                            <%= item.title %>
                          <% end %>
                        <!-- 日付の比較ここまで -->
                      </li>
                    <% end %>
                  <% end %>
              </ul>
            </li>
      </nav>
    </div>
  </div>