config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'carts/confirm'
  get 'about' => 'users#about', as: "about"
  get 'events/new/:id' => 'events#new', as: 'new_event'
  get 'items/new/:id' => 'items#new', as: 'new_item'

  devise_for :managers
  devise_for :users

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :following_artists, only: [:create, :destroy]
  end
  resources :artists do
    resource :following_artists, only: [:create, :destroy]
    resource :items, only: [:show, :index, :edit, :create, :destroy]
    resource :events, only: [:show, :edit, :update, :create, :destroy]
  end
  resources :items, :only => [:new, :show, :index, :edit, :create, :update, :destroy] do
    resource :carts, only: [:create, :destroy]
  end
  resources :events, :only => [:new, :show, :edit, :create, :update, :destroy]
  resources :discs, :only => [:create, :update, :destroy]
  resources :musics, :only => [:create, :update, :destroy]
  resources :carts, :only => [:index, :create, :update, :destroy]

  resources :histories, :only => [:show, :index, :create, :update] do
    resource :cart_histories, only: [:create, :destroy]
  end
  resources :cart_histories, :only => [:create]
  resources :following_artists, :only => [:index, :show, :create, :destroy]
  resources :labels, :only => [:index, :edit, :new, :create, :update, :destroy]
  resources :genres, :only => [:new, :create, :edit, :update, :destroy]
  resources :types, :only => [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  patch 'users/d/:id' => 'users#unsubscribe', as: 'unsubscribe_user'

end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :following_artists, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :items, dependent: :destroy

	attachment :image

  validates :name, presence: true, length: {maximum: 20}
  validates :name_kana, presence: true, length: {maximum: 30}
  validates :intro, presence: true, length: {maximum: 200}

  def followed_by?(user)
    following_artists.where(user_id: user.id).exists?
  end

  class Artits < ActiveRecord::Base
    paginates_per 5
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :amount, presence: true
end

app/models/cart_history.rb
class CartHistory < ApplicationRecord
  belongs_to :history
  belongs_to :item
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :item
  has_many :musics, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true

  validates :name, presence: true, length: {maximum: 20}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 30}
  validates :detail, presence: true, length: {maximum: 200}
  validates :datetime, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :cart_histories, dependent: :destroy
  accepts_nested_attributes_for :cart_histories, allow_destroy: true

  enum status_id:{receptionist: 0,preparation: 1,shipped: 2,cancel: 3}
  enum payment_id:{no_choice:0 ,credit_card: 1,banking: 2,convenience_store: 3,cash: 4}

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :artist
  belongs_to :type
  belongs_to :genre
  belongs_to :label

  has_many :cart_histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :discs, dependent: :destroy

	attachment :image

  accepts_nested_attributes_for :discs, allow_destroy: true

  validates :title, presence: true, length: {maximum: 40}
  validates :price, presence: true, length: {maximum: 7}
  validates :stock, presence: true, length: {maximum: 7}

  validates :artist_id, presence: true
  validates :type_id, presence: true
  validates :genre_id, presence: true
  validates :label_id, presence: true

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :items
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :disc

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :histories, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :following_artists, dependent: :destroy


  validates :name, presence: true, length:{maximum: 20}
  validates :name_kana, presence: true
  validates :postal_code, presence: true, length: {is: 7}
  validates :address, presence: true
  validates :phone_number, presence: true, length:{maximum: 11}
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :jump_to_about, only: [:create]
  before_action :authenticate_user!


  def index
    @carts = User.find(current_user.id).carts.all
    @cart = Cart.new
  end



  def show
    @cart_history = User.find(current_user.id).cart_history.find(params[:id])
    @history = current_user.hitory.find(params[:id])
  end

  def confirm
    @user =User.find(current_user.id)
    @carts = @user.carts.all
    @carts.each do |cart|
      amount = cart.amount
      stock = cart.item.stock
      if amount > stock
        redirect_to carts_path, alert: '他のユーザーの商品の購入により、入力の数量を準備できません。購入数量を変更してください。'
      end
    end
    @history = @user.histories.new
  end

  def create
    @item = Item.find(params[:item_id])
    # 同じ商品のカートが既にあるか確認
    @cart = Cart.find_by(item_id: @item.id)
    if @cart.blank?
      # カートが存在しない場合、カートを新しく作る
      @cart = @item.carts.new(cart_params)
      @cart.item_id = @item.id
      @cart.user_id = current_user.id
      if @cart.save
        if @cart.amount > @item.stock
          @cart.destroy
          redirect_to item_path(@cart.item.id), alert: '入力した数量に対し、在庫数が足りません。もう一度やり直してください。'
          return
        end
        redirect_to carts_path, notice: 'カートに商品を追加しました'
      else
        redirect_to item_path(@cart.item.id), alert: '購入数量を入力してください'
      end

    else
      # カートが存在する場合、カートの数量を増やす
      add_amount = params[:cart][:amount].to_i
      if add_amount == 0
        redirect_to item_path(@cart.item.id), alert: '購入数量を入力してください'
        return
      end
      @cart.amount = @cart.amount + add_amount
      if @cart.amount > @item.stock
        redirect_to item_path(@cart.item.id), alert: '入力した数量に対し、在庫数が足りません。もう一度やり直してください。'
        return
      end
      @cart.save
      redirect_to carts_path, notice: 'カートに商品を追加しました'
    end
  end

  def update
    @cart = Cart.find(params[:id])
    if params[:cart][:amount].to_i > @cart.item.stock
      redirect_to carts_path, alert: '入力した数量に対し、在庫数が足りません。購入数量を変更してください。'
      return
    end
    if @cart.update(cart_params)
      redirect_to carts_path, notice: '数量を変更しました'
    else
      redirect_to carts_path, alert: '数量の変更に失敗しました'
    end
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    redirect_to carts_path, notice: 'カートから商品を削除しました'
  end

  def jump_to_about
    if user_signed_in?
    else
      redirect_to about_path, notice: '商品の購入には、会員登録・ログインが必要です。'
    end
  end

  private
  def cart_params
    params.require(:cart).permit(:user_id, :item_id, :amount)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/confirm.html.erb
<h3>カート内容確認</h3>

<div class="center-block cart-item-tag">
  <p>カート内の商品</p>
</div>

<div class="cart-block center-block">
    <div>
      <% total_price = 0 %>
        <% @carts.each do |cart| %>
          <div class="cart-item-box">
            <div class="cart-box">
              <%= attachment_image_tag cart.item , :image, :fill, 250, 250, class:"cart_box", fallback: "no_image.png" %>
            </div>
            <div class="cart-box cart-item">
              <font size="4"><b><%= cart.item.title %></b></font>
              <p><%= cart.item.artist.name %></p>
            </div>
          <div class="cart-box cart-item">
            <p>数量：<%= cart.amount %></p>
            <p>価格：<%= cart.item.price %>円（税込）</p>
          </div>
          <% total_price = total_price + cart.amount * cart.item.price %>
          </div>
        <% end %>
    </div>

    <div class="cart-box2">
      <div class="cart-total">
        お買い物合計金額<br>
        <span class="total-price"><%= total_price %>円</span>（税込）
      </div>
    </div>


    <div class="destination-tag confirm-item">
      <b>送付先</b><br>
      <%= current_user.address %>
    </div>
    <div class="address-box confirm-item">
      <p>※住所を変更する方は、<br>
      マイページから編集をお願い致します。</p>
      <%= link_to "マイページから編集", user_path(current_user), class: 'btn btn-default' %>
    </div>

    <%= form_for(@history) do |f| %>

    <div class="payment-select-box">
      <b>支払方法</b><br>
      <%= f.radio_button :payment_id, :no_choice, checked: true, id:'invisible' %> 
      <%= f.radio_button :payment_id, :credit_card %>クレジットカード 
      <%= f.radio_button :payment_id, :banking %>銀行振込 
      <%= f.radio_button :payment_id, :convenience_store %>コンビニ支払 
      <%= f.radio_button :payment_id, :cash %>代金引換 
    </div>
</div>
<div class="center-block cart-box3">
  <p class="">
    以上の内容で購入します。<br>よろしければ「購入」、<br>内容を変更する場合は「カートに戻る」を<br>クリックしてください。
  </p>
  <div class="cart-btn">
    <%= link_to "カートに戻る",carts_path, class: "btn btn-default" %>
  </div>
  <div class="cart-btn">
    <%= f.submit "購入", class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/carts/index.html.erb
<h3>ショッピングカート</h3>
<div class="center-block">
  <div class="cart-item-tag">
    <p>カート内の商品</p>
  </div>


  <% total_price = 0 %>
  <% @carts.each do |cart| %>
    <%= form_for(cart) do |f| %>
      <div class="cart-item-box">
        <div class="cart-box">
          <%= attachment_image_tag cart.item , :image, :fill, 250, 250, class:"cart-box", fallback: "no_image.png" %>
        </div>
        <div class="cart-box cart-item">
          <font size="5"><b><%= link_to cart.item.title, item_path(cart.item.id) %></b></font>
            <br>
            <p><%= link_to cart.item.artist.name, artist_path(cart.item.artist.id) %></p>
        </div>

        <div class="cart-box cart-item">
          数量 : <%= f.text_field :amount, value:"#{cart.amount}" %>
          <p>在庫数 : <%= cart.item.stock %></p>
          <p>単価（税込）: <%= cart.item.price %>円</p>
          <div class="cart-btn"><%= f.submit "更新",class: 'cart-update btn' %></div>
          <div  class="cart-btn"><%= link_to "削除", cart_path(cart), class: 'cart-delete btn', method: :delete %></div>
        </div>
      </div>
      <% sub_total = cart.amount.to_i * cart.item.price.to_i %>
      <% total_price = total_price + sub_total %>
    <% end %>
  <% end %>
  <div class="cart-box2">
    <div class="cart-total">
      お買い物合計金額<br>
      <span class="total-price"><%= total_price %>円</span>（税込）
      <div>
        <%= link_to "購入手続きへ進む", carts_confirm_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="buy-btn">
    <%= link_to "戻る", :back, class: 'btn btn-default' %>
  </div>
</div>